# Generated by Django 2.1.7 on 2020-11-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcgData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_begin_time', models.DateField(auto_now=True)),
                ('ecg_time', models.CharField(max_length=128)),
                ('ecg_path', models.TextField()),
                ('ecg_hz', models.CharField(max_length=128)),
                ('ecg_img', models.TextField()),
                ('ecg_result', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=5)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=256)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
                'ordering': ['-creat_time'],
            },
        ),
        migrations.AddField(
            model_name='ecgdata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Person'),
        ),
    ]
